### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by PocketMine-GAD** [Yupai/NoDrops#1]
why not create a config that can set can-drop items and can't-drop items?

**Comment by Yupai** [comment]
Thank you for your suggestion. I'll try to do it.

**Comment by Yupai** [comment]
I do not know how to do that. I am sorry :(

**Comment by PocketMine-GAD** [comment]
i think we can work together and make this plugin perfect!:)
if you like,tell me!

**Comment by PocketMine-GAD** [comment]
how about those changes?[https://github.com/PocketMine-GAD/NoDrops/commit/27fdcde13f91d3a2468a97ea49b0ceb1948da614](url)

**Comment by PocketMine-GAD** [comment]
how about those changes?[https://github.com/PocketMine-GAD/NoDrops/commit](url)
